version: '2'
services:
    greatbigexampleapplication-app:
        image: greatbigexampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbb:sql://greatbigexampleapplication-postgresql:5432/GreatBigExampleApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=greatbigexampleapplication-elasticsearch:9300
        ports:
